### ISSUE TITLE
Zamiana lm na glm

### ISSUE THREAD

**Issue by mstaniak** [MI2DataLab/live#12]
albo jeszcze bardziej elastyczne narzedzie

ew mozliwosc wyboru lm/GLM/GAM/cos jeszcze za pomoca interfejsu mlr

**Comment by pbiecek** [comment]
każdy model mógłby być białą skrzynką (np. GAM) jeżeli jest jakiś naturalny sposób wizualizacji tego modelu. Nie wiem czy dla GAM jest coś gotowego w ggplot2
