### ISSUE TITLE
ranger is not working with live

### ISSUE THREAD

**Issue by pbiecek** [MI2DataLab/live#27]
In the new use-case (https://github.com/MI2DataLab/live/blob/master/vignettes/TCGA.Rmd)
I was using ranger package to build quickly a forest.
But something is wrong with the `predict` interface. I am getting following error

```
> similar <- simulateSimilar(data = nData,
+                            newData = nData[1,], 
+                            blackBox = trees, 
+                            explainedVar = "survival_status", 
+                            size = 50)
Error in "gwaa.data" %in% class(data) : 
  argument "data" is missing, with no default
```

**Comment by pbiecek** [comment]
btw, it's working with randomForest
```
trees <- randomForest(survival_status~., data = nData)
```
but something is in the interface for `ranger` that causes this bizarre error

**Comment by mstaniak** [comment]
i'll look into this

**Comment by pbiecek** [comment]
thanks but since randomForest is working, then this is a low priority issue

**Comment by mstaniak** [comment]
In ranger we have: predict(object, data, ...), usually it's predict(object, newdata, ...), so making a custom function predict_new <- function(object, newdata, ...) predict(object, data = newdata, ...) solve the issues. Closing.
