### ISSUE TITLE
object 'satisfaction_level' not found

### ISSUE THREAD

**Issue by asheetal** [MI2DataLab/live#60]
I am running the tutorial  provided  on this link 
https://mi2datalab.github.io/live/articles/HR.html

I get an error on the above tutorial
> similar1 <- add_predictions(HR_data, similar, black_box_model = trees)
Error in eval(predvars, data, env) : 
  object 'satisfaction_level' not found

Is there a mistake in the tutorial?

**Comment by mstaniak** [comment]
Hi,

currently the package has one vignette ("Wine quality"). "HR" and "TCGA" are not a part of the package anymore and they are terribly outdated.
For working examples, please see
https://mi2datalab.github.io/live/articles/wine_quality.html
and
https://journal.r-project.org/archive/2018/RJ-2018-072/index.html
or examples from the package documentation.

Please let me know if we can close this issue (AKA if the provided examples are okay).

**Comment by asheetal** [comment]
Thanks for quick response. The above tutorial has two issues as well. I was able to get it working by adding these three  lines of code
>wine_copy <- wine
>names(wine_copy) <- c("fixed.acidity", "volatile.acidity", "citric.acid", "residual.sugar", "chlorides", 
                  "free.sulfur.dioxide", "total.sulfur.dioxide", "density", "pH", "sulphates",
                  "alcohol", "quality", "label")
>wine_copy$label <- as.factor(wine_copy$label)
