### ISSUE TITLE
live::local_approximation results with a bug

### ISSUE THREAD

**Issue by harell** [MI2DataLab/live#61]
Using the provided example in the function documentation, the following bug appears

```
data('wine')
library(randomForest)
library(DALEX)
rf <- randomForest(quality~., data = wine)
expl <- explain(rf, wine, wine$quality)
live_expl <- live::local_approximation(expl, wine[5, ], "quality", 500)
```

```
Error in opts$show.learner.output || inherits(learner, "OptWrapper") : 
  invalid 'x' type in 'x || y'
```

Any ideas on how to fix it?

Thanks

**Comment by mstaniak** [comment]
Try 

```
library(live)
```

Before running that code. Did it work?

**Comment by mstaniak** [comment]
Btw there is a [localModel](https://github.com/ModelOriented/localModel) package that implements a newer version of live, though it is not on CRAN. It doesn't use the `mlr` backend.

**Comment by harell** [comment]
> Btw there is a [localModel](https://github.com/ModelOriented/localModel) package that implements a newer version of live, though it is not on CRAN. It doesn't use the `mlr` backend.

Thanks. 
Following the instruction, i.e. installing remotes v. 2.0.4.9000 the localModel package still fails to install and prompts the error

```
Error in read.dcf(path) : 
Found continuation line starting '  Przemyslaw Biecek  ...' at begin of record.
```

**Comment by mstaniak** [comment]
The `localModel` package is on CRAN now, so there won't be installation problems anymore. 
`localModel` and `live` take different approaches, btw.
