### ISSUE TITLE
Transfer live from MI2DataLab to ModelOriented

### ISSUE THREAD

**Issue by pbiecek** [MI2DataLab/live#63]
Let's move the  MI2DataLab/live package to  ModelOriented/live. All DrWhy projects will be in one organization.
Suggested date for the movement: August 21st

**Comment by mstaniak** [comment]
You mean date as deadline or as the exact date to do it? Why not move right now?

**Comment by pbiecek** [comment]
Few reasons:
- not surprise users
- have Time for discussion if it's a good choice
- synchronize transfers for other packages (around 10 of them)
- prepare single information for r bloggers that we moved all packages

**Comment by mstaniak** [comment]
@pbiecek transfer moved to today?

**Comment by pbiecek** [comment]
DALEX, auditor and randomForestExplainer went today
rest will go tomorrow

**Comment by mstaniak** [comment]
I don't have a permission to move the repo, so it's your call. Once it's in ModelOriented, I will update the links

**Comment by pbiecek** [comment]
transfered

**Comment by mstaniak** [comment]
Thanks. CI & Codecov seem to work, I update link to Github pages, all the links in README and DESCRIPTION & Zenodo DOI. I think that's all

**Comment by pbiecek** [comment]
Great, thanks
