### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by mstaniak** [MI2DataLab/live#7]
opisujące jakość dopasowania modelu

**Comment by mstaniak** [comment]
duża różnorodnośc modeli - czarnych skrzynek

**Comment by pbiecek** [comment]
jakość dopasowania białego modelu można dla klasyfikacji pokazać przez krzywe ROC
to byłby jednolity sposób przedstawiania dopasowania klasyfikatorów

**Comment by mstaniak** [comment]
closing, because no progress will be made in nearest future
noted as an idea for grant proposal
